import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { importHistory, createPack, validatePack, toMarkdown, fromMarkdown, checkSources, renderPrompt, sha256 } from '../src/core.mjs';
import { conformanceFiles } from '../scripts/generate-conformance-fixtures.mjs';

const directory = new URL('../examples/conformance/', import.meta.url);
const read = filename => readFileSync(new URL(filename, directory), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const packFor = name => JSON.parse(read(manifest.cases.find(entry => entry.name === name).pack));
const throwsCode = (fn, code) => assert.throws(fn, error => error.code === code);

test('published conformance files are generated by the current producer and explicitly synthetic', () => {
  assert.equal(manifest.synthetic, true);
  assert.deepEqual(manifest.cases.map(entry => entry.name), ['full-message', 'partial-message', 'unknown-source', 'rollout']);
  assert.ok(manifest.cases.every(entry => entry.receiverApprovalRequired === true));
  for (const [filename, text] of conformanceFiles()) assert.equal(read(filename), text, filename);
});

for (const entry of manifest.cases) {
  test(`${entry.name}: source-backed hash/range/provenance and JSON/Markdown round trips`, () => {
    const history = importHistory(read(entry.source), { sourceUri: entry.sourceUri });
    const pack = validatePack(JSON.parse(read(entry.pack)));
    const regenerated = createPack(history, entry.selections, { question: pack.question });
    for (const [index, excerpt] of pack.excerpts.entries()) {
      const source = history.messages.find(message => message.localId === excerpt.sourceLocalId);
      assert.equal(excerpt.sourceHash, sha256(source.text), 'sourceHash hashes the entire imported message text view');
      assert.equal(excerpt.excerptHash, sha256(excerpt.exactText));
      assert.equal(excerpt.exactText, source.text.slice(excerpt.range.start, excerpt.range.end));
      assert.equal(excerpt.sourceLength, source.text.length);
      const { id: ignoredSavedId, ...saved } = excerpt;
      const { id: ignoredGeneratedId, ...produced } = regenerated.excerpts[index];
      assert.deepEqual(saved, produced);
    }
    assert.deepEqual(validatePack(JSON.parse(JSON.stringify(pack))), pack);
    assert.deepEqual(fromMarkdown(read(entry.markdown)), pack);
    assert.equal(toMarkdown(pack), read(entry.markdown));
    assert.deepEqual(checkSources(pack, history).map(item => item.status), pack.excerpts.map(() => entry.name === 'unknown-source' ? 'missing' : 'unchanged'));
  });
}

test('partial, unknown and rollout fixtures retain legal distinctions consumers must not narrow', () => {
  const partial = packFor('partial-message').excerpts[0];
  assert.notEqual(partial.sourceHash, partial.excerptHash);
  assert.ok(partial.range.start > 0 && partial.range.end < partial.sourceLength);
  assert.ok(partial.exactText.includes('😀'));
  assert.ok(!JSON.stringify(packFor('partial-message')).includes('未选前文'));
  const unknown = packFor('unknown-source').excerpts[0];
  for (const key of ['sourceThreadId', 'sourceTurnId', 'sourceItemId', 'sourceUri', 'timestamp']) assert.equal(unknown[key], null);
  for (const excerpt of packFor('rollout').excerpts) {
    assert.equal(excerpt.sourceKind, 'codex-rollout');
    assert.equal(excerpt.sourceThreadId, 'fixture-rollout-session');
    assert.equal(excerpt.sourceTurnId, 'fixture-rollout-turn');
    assert.equal(excerpt.sourceItemId, null, 'import ordinal is not a host message ID');
  }
});

test('conformance imports preserve background status and inclusion without approving proposals', () => {
  for (const entry of manifest.cases) {
    const pack = packFor(entry.name);
    assert.deepEqual(fromMarkdown(toMarkdown(pack)).memory, pack.memory);
    for (const memory of pack.memory.filter(item => !item.included)) assert.ok(!renderPrompt(pack).includes(memory.text));
  }
  const partial = packFor('partial-message');
  assert.equal(partial.memory[0].status, 'model-proposed');
  assert.equal(partial.memory[0].included, false);
  const invalid = structuredClone(partial); invalid.memory[0].included = true;
  throwsCode(() => validatePack(invalid), 'UNCONFIRMED_MEMORY');
  invalid.memory[0].included = false;
  assert.deepEqual(validatePack(invalid), partial, 'recovery removes accidental inclusion without changing approval status');
  assert.ok(!Object.hasOwn(partial, 'approved'), 'receiver approval is outside the ContextPack protocol');
});

test('fixture corruption, old field names and orphaned background fail; original packages remain recoverable', () => {
  const original = packFor('full-message');
  const altered = structuredClone(original); altered.excerpts[0].exactText = '预算上限为每月 900 元。';
  throwsCode(() => validatePack(altered), 'INTEGRITY_MISMATCH');
  const oldNames = { ...original, items: original.excerpts, background: original.memory, provenance: {} };
  delete oldNames.excerpts; delete oldNames.memory;
  throwsCode(() => validatePack(oldNames), 'INVALID_PACK');
  const orphaned = structuredClone(original); orphaned.excerpts.shift();
  throwsCode(() => validatePack(orphaned), 'ORPHANED_MEMORY');
  throwsCode(() => fromMarkdown(toMarkdown(original).replace('预算上限为每月 300 元。', '预算上限为每月 900 元。')), 'MARKDOWN_TAMPERED');
  assert.deepEqual(fromMarkdown(read('full-message.pack.md')), original);
  const entry = manifest.cases.find(item => item.name === 'full-message');
  const source = JSON.parse(read(entry.source));
  const changed = structuredClone(source); changed.thread.turns[0].items[0].content[0].text = '来源已修改。';
  assert.equal(checkSources(original, importHistory(changed, { sourceUri: entry.sourceUri }))[0].status, 'changed');
  changed.thread.turns[0].items.shift();
  assert.equal(checkSources(original, importHistory(changed, { sourceUri: entry.sourceUri }))[0].status, 'missing');
  assert.ok(checkSources(original, importHistory(source, { sourceUri: entry.sourceUri })).every(item => item.status === 'unchanged'));
  assert.deepEqual(original, packFor('full-message'));
});
